import 'dart:io';
import 'package:dart_openai/dart_openai.dart';
import 'package:path/path.dart' as path;
import 'package:shared_preferences/shared_preferences.dart';

class AppGenerationService {
  Future<String> generateApp(String prompt) async {
    final prefs = await SharedPreferences.getInstance();
    final llmProvider = prefs.getString('llm_provider') ?? 'OpenAI';
    final apiKey = prefs.getString('api_key');

    if (apiKey == null) {
      throw Exception('API key not found');
    }

    String code;
    if (llmProvider == 'OpenAI') {
      OpenAI.apiKey = apiKey;
      final completion = await OpenAI.instance.completion.create(
        model: "text-davinci-003",
        prompt: "Generate a Flutter app with the following description: $prompt",
      );
      code = completion.choices.first.text;
    } else {
      // TODO: Implement Google LLM
      throw UnimplementedError('Google LLM not implemented');
    }

    final tempDir = await Directory.systemTemp.createTemp();
    final libDir = await Directory(path.join(tempDir.path, 'lib')).create();
    await File(path.join(libDir.path, 'main.dart')).writeAsString(code);
    await File(path.join(tempDir.path, 'firestore.rules')).writeAsString("""
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if true;
    }
  }
}
""");
    await File(path.join(tempDir.path, 'README.md')).writeAsString("""
# Generated App

This app was generated by AppVibe.

## Firebase Rules

To use the Firebase rules, you need to deploy them to your Firebase project. You can do this by running the following command in your terminal:

```
firebase deploy --only firestore:rules
```
""");

    return tempDir.path;
  }
}
